[package]
name = "fernanda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.12.1", features = ["serde-json"] }
base64 = "0.21.5"
chrono = { version = "0.4.31", features = ["serde"] }
poem = { version = "1.3.59", features = ["session", "static-files"] }
poem-openapi = { version = "3.0.5", features = ["swagger-ui", "chrono"] }
serde = "1.0.193"
serde_json = "1.0.107"
shuttle-poem = "0.34.1"
shuttle-runtime = "0.34.1"
shuttle-secrets = "0.34.1"
shuttle-shared-db = { version = "0.35.0", features = ["postgres"] }
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio-rustls", "chrono", "postgres"] }
strum = { version = "0.25.0", features = ["strum_macros", "derive"] }
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread", "sync"] }
tracing = "0.1.39"
tracing-subscriber = "0.3.18"
